@extends ('layouts.master')

    @section('body-class')body--landingpage @stop

    @section('content')

        <section>

            <h1>screeenly - a simple Screenshot API</h1>
            <p>Screeenly is a free webapplication which developers can use to generate Screenshots of websites.</p>

            <p>
                {!! link_to_route('login', 'Sign up with Github', null, ['class' => 'button']) !!}
                <br><small>We currently only support Login with Github. An email address is required.</small>
            </p>

            <p>You can see <a href="#show-examples">examples</a> below or {!! link_to_route('try', 'test it') !!} right now for!</p>

            <hr class="divider">

            <h2 id="show-examples">Example screenshots</h2>
            <p>All of the following screenshots were generated by Screeenly.</p>

            <figure>
                <img src="{!! URL::asset('assets/images/examples/bbc-com.jpg') !!}" alt="Screenshot of BCC.com">
                <figcaption>http://bbc.com</figcaption>
            </figure>

            <figure>
                <img src="{!! URL::asset('assets/images/examples/medium.jpg') !!}" alt="Screenshot of Medium.com">
                <figcaption>http://medium.com</figcaption>
            </figure>

            <figure>
                <img src="{!! URL::asset('assets/images/examples/facebook.jpg') !!}" alt="Screenshot of Facebook.com">
                <figcaption>http://facebook.com</figcaption>
            </figure>

            <hr class="divider">

            <a href="#top-link">Back to the top.</a>

        </section>


    @stop